trees
str(trees)
dim(trees)
is.na(trees)
N_trees<-na.omit(trees)# 결측치 제거
is.na(N_trees)
dim(N_trees)
sum(is.na(trees))
colnames(trees)
mean(trees$Girth)
mean(trees$Height)
mean(trees$Volume)
summary(trees)
hist(trees$Girth)
hist(trees$Height)
##줄기 잎 그림
stem(trees$Girth)
stem(trees$Height)
stem(trees$Volume)
boxplot(trees$Girth)
boxplot(trees$Height)
boxplot(trees$Volume)
boxplot(trees)
##상관관계
##correlation coefficient
cor(trees)
##plot(x,y)
plot(trees$Girth, trees$Height)
plot(trees$Girth, trees$Volume)
##linear Regression 1차 직선회귀모델
##lm(y - x)
fit<-lm(trees$Volume~trees$Girth, data = trees)
abline(fit)
fit2<-lm(trees$Volume~trees$Height, data = trees)
plot(trees$Height, trees$Volume)
abline(fit2)
predict(fit2)
predict(fit2)
summary(fit2)
abline(fit2)
predict(fit)
predict(fit2)
plot(trees$Height, trees$Volume)
fit2<-lm(trees$Volume~trees$Height, data = trees)
##lm : 1차 회귀 모델
##summary : 1차 회귀 모델 실용평가
##predict : 예측값 효력
plot(trees$Height, trees$Volume)
fit2<-lm(trees$Volume~trees$Height, data =trees)
abline(fit2)
summary(fit2)
library(psych)
hist(trees$Girth, probability = T)
lines(density(trees$Girth), col = "red")
hist(trees$Height, probability = T)
lines(density(trees$Height), col = "red")
hist(trees$Volume, probability = T)
lines(density(trees$Volume), col = "red")
hist(trees$Volume)
lines(trees$Volume, col = "red")
Vol_norm=rnorm(10000, mean(trees$Volume), sd(trees$Volume))
lines(density(Vol_norm, col = "blue"))
mean(trees$Volume)
sd(trees$Volume)
